program: eval_peadmm.py
project: peadmm-rim-sweeep
name: sweep-peadmm-spi-cr01-val
method: bayes
metric:
  name: peadmm/psnr
  goal: maximize
parameters:
  root:
    value: data
  task:
    value: spi
  split:
    value: val
  device:
    value: cuda
  generator-checkpoint:
    value: results/generator_wgangp_mnist32_e500_bs128_glr_1e-4_dlr_1e-4_z128_ch64_gp10_crit5_elu/generator.pt
  encoder-checkpoint:
    value: results/encoder_spi_mnist32_cr_1e-1_e500_bs128_lr_1e-3_z128_ch64/encoder.pt
  batch-size:
    values: [128]
  num-workers:
    value: 0
  cr:
    value: 0.1
  measurement-noise-std:
    values: [0.0]
  iterations:
    values: [2500]
  max-examples:
    values: [100]
  gamma:
    values: [1.0, 10.0, 25.0, 50.0, 100.0, 200.0]
  beta:
    values: [0.005, 0.01, 0.02, 0.05, 0.1, 1.0]
  sigma:
    values: [0.005, 0.01, 0.02, 0.05, 0.1, 1.0]
  wandb-group:
    value: sweep-peadmm-spi-cr01-val
  wandb-job-type:
    value: sweep_eval_peadmm
  wandb-tags:
    value: sweep,bayes,peadmm,spi,cr01,val
command:
  - ${env}
  - python
  - -m
  - eval_peadmm
  - ${args}
